import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Generate JSON report
export function generateJsonReport(results, outputPath) {
  const report = {
    timestamp: new Date().toISOString(),
    summary: {
      total: results.length,
      critical: results.filter(r => r.severity === 'critical').length,
      high: results.filter(r => r.severity === 'high').length,
      medium: results.filter(r => r.severity === 'medium').length,
      low: results.filter(r => r.severity === 'low').length,
      info: results.filter(r => r.severity === 'info').length,
    },
    findings: results,
  };

  fs.writeFileSync(outputPath, JSON.stringify(report, null, 2));
  return report;
}

// Generate Markdown report
export function generateMarkdownReport(results, outputPath) {
  const timestamp = new Date().toISOString();
  const summary = {
    critical: results.filter(r => r.severity === 'critical'),
    high: results.filter(r => r.severity === 'high'),
    medium: results.filter(r => r.severity === 'medium'),
    low: results.filter(r => r.severity === 'low'),
    info: results.filter(r => r.severity === 'info'),
  };

  let md = `# Security Scan Report

**Generated:** ${timestamp}

## Summary

| Severity | Count |
|----------|-------|
| Critical | ${summary.critical.length} |
| High | ${summary.high.length} |
| Medium | ${summary.medium.length} |
| Low | ${summary.low.length} |
| Info | ${summary.info.length} |
| **Total** | **${results.length}** |

---

`;

  // Group findings by type
  const byType = {};
  for (const finding of results) {
    const type = finding.type || 'other';
    if (!byType[type]) byType[type] = [];
    byType[type].push(finding);
  }

  for (const [type, findings] of Object.entries(byType)) {
    md += `## ${formatType(type)}

`;

    for (const finding of findings) {
      const severityBadge = getSeverityBadge(finding.severity);

      md += `### ${severityBadge} ${finding.description || finding.type}

`;

      if (finding.location) {
        md += `**Location:** \`${finding.location}\`

`;
      } else if (finding.file) {
        const relativePath = finding.file.replace(/.*[\\\/]src[\\\/]/, 'src/').replace(/\\/g, '/');
        md += `**File:** \`${relativePath}\`

`;
      }

      if (finding.package) {
        md += `**Package:** ${finding.package} (${finding.version})

`;
      }

      if (finding.header) {
        md += `**Header:** ${finding.header}

`;
      }

      if (finding.payload) {
        md += `**Payload:** \`${finding.payload}\`

`;
      }

      if (finding.field) {
        md += `**Field:** ${finding.field}

`;
      }

      if (finding.line) {
        md += `**Line:** ${finding.line}

`;
      }

      if (finding.code) {
        md += `**Code:** \`${finding.code}\`

`;
      }

      if (finding.recommendation) {
        md += `**Fix:** ${finding.recommendation}

`;
      }

      if (finding.url) {
        md += `**Reference:** ${finding.url}

`;
      }

      md += `---

`;
    }
  }

  if (results.length === 0) {
    md += `## No Issues Found

No security vulnerabilities were detected in this scan.

---

`;
  }

  md += `## Next Steps

1. Address all **Critical** and **High** severity issues immediately
2. Review **Medium** severity issues and plan remediation
3. Consider **Low** severity issues for future improvements
4. Re-run this scan after making changes

---

*Generated by Neural Solutions Security Scanner*
`;

  fs.writeFileSync(outputPath, md);
}

// Print terminal summary
export function printTerminalSummary(results) {
  const summary = {
    critical: results.filter(r => r.severity === 'critical').length,
    high: results.filter(r => r.severity === 'high').length,
    medium: results.filter(r => r.severity === 'medium').length,
    low: results.filter(r => r.severity === 'low').length,
    info: results.filter(r => r.severity === 'info').length,
  };

  console.log('\n' + '='.repeat(50));
  console.log('SECURITY SCAN RESULTS');
  console.log('='.repeat(50));
  console.log(`
  Critical: ${summary.critical}
  High:     ${summary.high}
  Medium:   ${summary.medium}
  Low:      ${summary.low}
  Info:     ${summary.info}
  ─────────────────
  Total:    ${results.length}
`);

  if (summary.critical > 0 || summary.high > 0) {
    console.log('⚠️  ACTION REQUIRED: Critical/High severity issues found!\n');
  } else if (summary.medium > 0) {
    console.log('⚡ Some issues found - review recommended.\n');
  } else {
    console.log('✓ No critical issues found.\n');
  }

  // Print top issues
  const topIssues = results
    .filter(r => r.severity === 'critical' || r.severity === 'high')
    .slice(0, 5);

  if (topIssues.length > 0) {
    console.log('Top Issues:');
    for (const issue of topIssues) {
      console.log(`  [${issue.severity.toUpperCase()}] ${issue.description || issue.type}`);
      if (issue.location) console.log(`           ${issue.location}`);
    }
    console.log('');
  }

  console.log('Reports generated:');
  console.log('  - security/report.json');
  console.log('  - security/report.md');
  console.log('='.repeat(50) + '\n');
}

function formatType(type) {
  const typeMap = {
    'other': 'Static Analysis',
    'dangerous-pattern': 'Dangerous Code Patterns',
    'dependency-vulnerability': 'Dependency Vulnerabilities',
    'missing-security-header': 'Missing Security Headers',
    'weak-security-header': 'Weak Security Headers',
    'cors-misconfiguration': 'CORS Misconfiguration',
    'reflected-xss': 'Reflected XSS',
    'potential-dom-xss': 'Potential DOM XSS',
    'potential-stored-xss': 'Potential Stored XSS',
    'connection-error': 'Connection Issues',
    'audit-error': 'Audit Errors',
  };

  if (typeMap[type]) return typeMap[type];

  return type
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

function getSeverityBadge(severity) {
  const badges = {
    critical: '🔴 CRITICAL',
    high: '🟠 HIGH',
    medium: '🟡 MEDIUM',
    low: '🟢 LOW',
    info: 'ℹ️ INFO',
  };
  return badges[severity] || '⚪ UNKNOWN';
}
